---

- name: Install dependencies
  apt: pkg=python-pycurl

- name: Add nginx repository
  apt_repository: repo=ppa:nginx/stable
  when: nginx_apt_use_repo

- name: Install Dependencies
  apt: pkg={{item}}
  with_items: [ nginx, python-passlib ] 
